import os
import threading
from time import sleep
import webbrowser
import matplotlib.pyplot as plt
import ast
from io import BytesIO
from flask import Flask, render_template, send_file, redirect, url_for, request
from socket import socket

# Flask app
app = Flask(__name__)

# Network socket
sock = socket()

# Every data reading received from storage
storage_log = []

# Update interval for getting data from client
interval = 1


def init_socket():
    """
    Start socket to connect to server using TCP
    """
    server_address = ("localhost", 5556)
    sock.connect(server_address)


@app.route('/')
def hello_world():
    """
    This function runs when the flask web page is loaded to / (root)

    :return: HTML template for webpage
    """
    return render_template('index.html')


@app.route('/', methods=['POST', 'GET'])
def handle_request():
    """
    This function is called whenever a post or get request is sent from the webpage
    Sends a message to storage server to send all data available,
    then updates readings and subsequently the GUI Plot in webpage

    :return: Template from hello_world()
    """
    sentence = "give all"
    sock.send(sentence.encode())

    update_all_readings()
    graph_plot()

    # Return new page (currently only updating image so have to return new html site)
    return hello_world()


@app.route('/graph.png')
def graph_plot():
    """
    File graph.png used by webpage
    Gets image generated by pyplot helper function get_plot

    :return: send_file function to @app.route args location
    """
    img = get_plot()
    return send_file(img, mimetype='image/png', cache_timeout=0)


def update_all_readings():
    """
    Updates local storage data to new data received over TCP,
    Then formats as floats to store locally

    :rtype: None
    """
    # Clear all storage data
    storage_log.clear()

    # Get temperature and precipitation data (big buffer size to handle a long list of data)
    raw_data = sock.recv(1000000).decode()

    while raw_data.find(']') > -1:  # find returns -1 when arg not found
        # Get all items in temperature list
        temperature_data = list_to_string(raw_data)

        # Removes temperature list from the raw data
        raw_data = raw_data[raw_data.index(']') + 1:]

        # Get all items in precipitation list
        precipitation_data = list_to_string(raw_data)
        raw_data = raw_data[raw_data.index(']') + 1:]

        # Convert all string data to float
        temperature_float = [float(i) for i in temperature_data]
        precipitation_float = [float(i) for i in precipitation_data]

        storage_log.append((temperature_float, precipitation_float))
    print("Client readings updated from storage.")


def list_to_string(raw_data):
    """
    We get a list in string format so ast_eval converts it to a string

    :return: Segment of raw data
    """
    return ast.literal_eval(raw_data[:raw_data.index(']') + 1])


def get_plot():
    """
    Generate pyplot image from weather data
    Generates two separate axis from plt.subplot to send to each axis plotting function

    :rtype: img
    """
    plt.clf()
    fig, (ax_72, ax_all) = plt.subplots(nrows=2)
    fig.tight_layout(pad=5.0)
    fig.set_figheight(8)
    fig.set_figwidth(16)
    get_72(ax_72)
    get_all(ax_all)
    img = BytesIO()
    plt.savefig(img)
    img.seek(0)
    return img


def get_72(ax_72):
    """
    Write pyplot axis for 72 hours

    :param axis ax_72: Axis to write to
    """
    if len (storage_log) > 0:
        ax_72.plot(storage_log[len(storage_log)-1][0], color='red')    # temp
        ax_72.plot(storage_log[len(storage_log)-1][1], color='blue')   # prec
    ax_72.set_ylabel('Temp(C), Prec (mm)')
    ax_72.set_xlabel('Time (hours)')
    ax_72.set_title('Precipitation (blue), Temperature (red) (72 hours)')


def get_all(ax_all):
    """
    Write pyplot axis for all hours

    :param axis ax_all: axis to write to
    """
    tempList = [x[0] for x in storage_log]
    temp_list = []
    for i in tempList:
        temp_list = temp_list+i

    precList = [x[1] for x in storage_log]
    prec_list = []
    for i in precList:
        prec_list = prec_list+i

    if len (storage_log) > 0:
        # Storage log has a list of tuples containing (72 hours of temp, 72 hours of precipitation)
        # First items in storage log, temperature
        ax_all.plot(temp_list, color='red')
        # Second items in storage log, precipitation
        ax_all.plot(prec_list, color='blue')
    ax_all.set_ylabel('Temp(C), Prec (mm)')
    ax_all.set_xlabel('Time (hours)')
    ax_all.set_title('Precipitation (blue), Temperature (red) (All time)')


def main():
    """
    Starts weather station and storage server,
    initializes socket then opens flask webpage at port 5000
    Magic numbers between each print to make the application a bit more readable to users
    """
    print("Starting storage and weather services...")
    ws = threading.Thread(target=run_weather_station)
    s = threading.Thread(target=run_storage)
    ws.start()
    s.start()
    sleep(1.2)
    print("> \t Weather station ready.")
    sleep(1.1)
    print("> \t Storage server ready.")
    sleep(0.5)
    print("Starting client TCP connection to server...")
    sleep(0.9)
    init_socket()
    print("> \t Connection ready.")
    sleep(0.7)
    print("Running flask app. Open your web browser and enter http://localhost:5000/")
    sleep(0.4)
    print("-----------------------------------READY--------------------------------")
    print("Here at FMI™ we are so kind and considerate that we open your web browser for you without asking!")
    sleep(1)
    webbrowser.open('http://localhost:5000/')
    app.run()


def run_weather_station():
    """
    Starts weather station server
    """
    os.system("python code/weather-station/weather-station-server.py")


def run_storage():
    """
    Starts storage server
    """
    os.system("python code/storage/storage.py")


if __name__ == '__main__':
    main()

main()
